CREATE TABLE USUARIO (
	CPF CHAR(11) PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	SENHA VARCHAR(16) NOT NULL,
	EMAIL VARCHAR(50) UNIQUE NOT NULL,
	ADMINISTRADOR BOOLEAN NOT NULL
);


CREATE TABLE AUTOR (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL
);

CREATE TABLE EDITORA (
	CNPJ CHAR(14) PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE LIVRO(
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	IMAGEM VARCHAR(200) UNIQUE NOT NULL,
	DESCRICAO VARCHAR(500) NOT NULL,
	VALOR NUMERIC(5,2) NOT NULL,
	FK_EDITORA CHAR(14) NOT NULL,
	FK_AUTOR INT NOT NULL,
	FOREIGN KEY (FK_EDITORA) REFERENCES EDITORA(CNPJ)
		ON UPDATE CASCADE
		ON DELETE NO ACTION,
	FOREIGN KEY (FK_AUTOR) REFERENCES AUTOR(ID)
		ON UPDATE CASCADE
		ON DELETE NO ACTION 
);

CREATE TABLE COMPRA(
	ID_LIVRO INT,
	ID_USUARIO CHAR(11),
	DATA_COMPRA DATE NOT NULL,
	PRIMARY KEY (ID_LIVRO,ID_USUARIO),
	FOREIGN KEY (ID_LIVRO) REFERENCES LIVRO(ID)
		ON UPDATE CASCADE
		ON DELETE NO ACTION,
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(CPF)
		ON UPDATE CASCADE
		ON DELETE NO ACTION
);
