CREATE TABLE USUARIO(
	ID SERIAL PRIMARY KEY,
	CPF CHAR(11) UNIQUE NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	SENHA VARCHAR(16) NOT NULL,
	EMAIL VARCHAR(50) UNIQUE NOT NULL,
	ADMINISTRADOR BOOLEAN NOT NULL
);

CREATE TABLE AUTOR(
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL
);

CREATE TABLE EDITORA(
	ID SERIAL PRIMARY KEY,
	CNPJ CHAR(14) UNIQUE NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE LIVRO(
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	IMAGEM VARCHAR(250) UNIQUE NOT NULL,
	DESCRICAO VARCHAR(500) NOT NULL,
	GENERO VARCHAR(100) NOT NULL,
	PRECO NUMERIC(5,2) NOT NULL,
	ID_EDITORA CHAR(14) NOT NULL,
	ID_AUTOR INT NOT NULL,
	FOREIGN KEY (ID_EDITORA) REFERENCES EDITORA(CNPJ)
		ON UPDATE CASCADE
		ON DELETE NO ACTION,
	FOREIGN KEY (ID_AUTOR) REFERENCES AUTOR(ID)
		ON UPDATE CASCADE
		ON DELETE NO ACTION 
);

CREATE TABLE COMPRA(
	ID_LIVRO INT,
	ID_USUARIO CHAR(11),
	DATA_COMPRA DATE NOT NULL,
	PRECO NUMERIC(5,2) NOT NULL,
	PRIMARY KEY (ID_LIVRO,ID_USUARIO),
	FOREIGN KEY (ID_LIVRO) REFERENCES LIVRO(ID)
		ON UPDATE CASCADE
		ON DELETE NO ACTION,
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(CPF)
		ON UPDATE CASCADE
		ON DELETE NO ACTION
);

CREATE TABLE AUTORLIVRO(
	ID_LIVRO INT,
	ID_AUTOR INT,
	PRIMARY KEY (ID_LIVRO,ID_AUTOR),
	FOREIGN KEY (ID_LIVRO) REFERENCES LIVRO(ID)
		ON UPDATE CASCADE
		ON DELETE NO ACTION,
	FOREIGN KEY (ID_AUTOR) REFERENCES AUTOR(ID)
		ON UPDATE CASCADE
		ON DELETE NO ACTION
);
